name: Compilar C++

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Descargar codigo fuente
      uses: actions/checkout@v4

    - name: Compilar programa
      run: g++ -o mi_programa main.cpp

    - name: Ejecutar programa
      run: ./mi_programa
